POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAArSfTdsw:APA91bHNA5RH3CFtudKiDuGeUZo1LgEwLcPcYWgDV9j4tOQ2bZ_EdMeU9Z-D9FbBJYox9JyTdHo_tozg01OUzPgU3HKIBomewC2hAkoYvWo8ZwqPRMfaZZZqzJneJILSdlnGaVZ_fU7f
project_id: 743697512140

{
  "to": "yZIfaPRQdytn6MJo_sU9B:APA91bHxG_mOmTMBjHnH_w1ujMs5nlS3eHe0qg-9UEj2RObuhHGVVhBiAQhvZAYvLmtMSDoRVn9vJlClCO2MI0o8JT51NQWNaspGfrbEPqHeLChcjyI6OQ10Uu2GLFWu5IbnEPJcPrGJ",
  "notification": {
    "title": "New trip request",
    "body": "body",
    "content_available": true,
    "sound": "res_ring.wav",
    "android_channel_id": "new_order"
  },
  "click_action": "FLUTTER_NOTIFICATION_CLICK",
  "priority": "high",
  "data": {
    "vahid": 22
  },
  "time_to_live": 20,
  "aps": {
    "alert": {
      "title": "title",
      "body": "desc"
    },
    "mutable-content": true
  }
}
